-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 10:37:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blog`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admin_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_admin_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `blog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`posts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(500) NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `subtitle` VARCHAR(500) NULL DEFAULT NULL,
  `content` LONGTEXT NULL DEFAULT NULL,
  `author` VARCHAR(100) NULL DEFAULT NULL,
  `date` TIMESTAMP NULL DEFAULT NULL,
  `admin_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_admin1_idx` (`admin_id` ASC) ,
  CONSTRAINT `fk_posts_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `blog`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blog`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `postId` INT(11) NOT NULL,
  `userId` INT(11) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `comment` TINYTEXT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `postId_idx` (`postId` ASC) ,
  CONSTRAINT `postId`
    FOREIGN KEY (`postId`)
    REFERENCES `blog`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blog`.`visitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`visitor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admin_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_admin_users10`
    FOREIGN KEY (`users_id`)
    REFERENCES `blog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blog`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`contact` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `message` TINYTEXT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `visitor_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_visitor1_idx` (`visitor_id` ASC) ,
  CONSTRAINT `fk_contact_visitor1`
    FOREIGN KEY (`visitor_id`)
    REFERENCES `blog`.`visitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blog`.`visitor_has_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`visitor_has_comments` (
  `visitor_id` INT(11) NOT NULL,
  `comments_id` INT(11) NOT NULL,
  PRIMARY KEY (`visitor_id`, `comments_id`),
  INDEX `fk_visitor_has_comments_comments1_idx` (`comments_id` ASC) ,
  INDEX `fk_visitor_has_comments_visitor1_idx` (`visitor_id` ASC) ,
  CONSTRAINT `fk_visitor_has_comments_visitor1`
    FOREIGN KEY (`visitor_id`)
    REFERENCES `blog`.`visitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visitor_has_comments_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `blog`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
